version: "3.7"

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-app
    restart: always
    ports:
      - "8081:80"
    networks:
      - vue-network
networks:
  vue-network:
    driver: bridge
